### ISSUE TITLE
I want to optimize this code

### ISSUE THREAD

**Issue by Vipin1090** [shakti1590/bubble-sort#10]
Please assign me.

**Comment by shakti1590** [comment]
ok, Vipin do it.

**Comment by saikishore222** [comment]
[optimized Code](https://github.com/shakti1590/bubble-sort/pull/6) I already made a PR that , can you please check and give review , make sure it under hactoberfest 2022.

**Comment by Anushree1291** [comment]
Can i also work on it. I can do it in java

**Comment by shakti1590** [comment]
> Can i also work on it. I can do it in java

sure

**Comment by shakti1590** [comment]
> [optimized Code](https://github.com/shakti1590/bubble-sort/pull/6) I already made a PR that , can you please check and give review , make sure it under hactoberfest 2022.

done

**Comment by Anushree1291** [comment]
I have also made a PR. Please do review. In case of error from my side do tell me. It's a great learning experience for me. Thank you.

**Comment by ananya-1112** [comment]
May I please work on this

**Comment by shakti1590** [comment]
> May I please work on this
sure

**Comment by Kali-13** [comment]
Can I add another sorting algorithm?
