### ISSUE TITLE
Want to Contribute CPP version of this Coding problem bubble-sort 

### ISSUE THREAD

**Issue by Chayandev** [shakti1590/bubble-sort#8]
**Want to add CPP version of Bubble-sort**

**Comment by Chayandev** [comment]
Please assign me this issue @shakti1590 I want to work on that.

**Comment by shakti1590** [comment]
ok, add into a new file.

**Comment by shakti1590** [comment]
If you want then do a pull request @Chayandev

**Comment by Chayandev** [comment]
Successfully done and merged my pull request,thank you .
